In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import DataFrame,Series
import seaborn as sns
import scipy.stats as stats

In [ ]:
train=pd.read_csv('/content/drive/MyDrive/train.csv')
test=pd.read_csv('/content/drive/MyDrive/test.csv')

In [ ]:
train.shape,test.shape

((1460, 81), (1459, 80))

In [ ]:
pd.options.display.max_rows=None
pd.options.display.max_columns=None

In [ ]:
train.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          8
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [ ]:
test.isna().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       227
LotArea             0
Street              0
Alley            1352
LotShape            0
LandContour         0
Utilities           2
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         1
Exterior2nd         1
MasVnrType         16
MasVnrArea         15
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           44
BsmtCond           45
BsmtExposure       44
BsmtFinType1       42
BsmtFinSF1          1
BsmtFinType2       42
BsmtFinSF2          1
BsmtUnfSF           1
TotalBsmtSF         1
Heating             0
HeatingQC           0
CentralAir          0
Electrical          0
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        2
BsmtHalfBath        2
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         1
TotRmsAbvGrd        0
Functional          2
Fireplaces          0
FireplaceQu       730
GarageType         76
GarageYrBlt        78
GarageFinish       78
GarageCars          1
GarageArea          1
GarageQual         78
GarageCond         78
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1456
Fence            1169
MiscFeature      1408
MiscVal             0
MoSold              0
YrSold              0
SaleType            1
SaleCondition       0
dtype: int64

In [ ]:
train.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
Alley             object
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
BsmtQual          object
BsmtCond          object
BsmtExposure      object
BsmtFinType1      object
BsmtFinSF1         int64
BsmtFinType2      object
BsmtFinSF2         int64
BsmtUnfSF          int64
TotalBsmtSF        int64
Heating           object
HeatingQC         object
CentralAir        object
Electrical        object
1stFlrSF           int64
2ndFlrSF           int64
LowQualFinSF       int64
GrLivArea          int64
BsmtFullBath       int64
BsmtHalfBath       int64
FullBath           int64
HalfBath           int64
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual       object
TotRmsAbvGrd       int64
Functional        object
Fireplaces         int64
FireplaceQu       object
GarageType        object
GarageYrBlt      float64
GarageFinish      object
GarageCars         int64
GarageArea         int64
GarageQual        object
GarageCond        object
PavedDrive        object
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
PoolQC            object
Fence             object
MiscFeature       object
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
dtype: object

In [ ]:
train.describe().T

,count,mean,std,min,25%,50%,75%,max
Id,1460.0,730.500000,421.610009,1.0,365.75,730.5,1095.25,1460.0
MSSubClass,1460.0,56.897260,42.300571,20.0,20.00,50.0,70.00,190.0
LotFrontage,1201.0,70.049958,24.284752,21.0,59.00,69.0,80.00,313.0
LotArea,1460.0,10516.828082,9981.264932,1300.0,7553.50,9478.5,11601.50,215245.0
OverallQual,1460.0,6.099315,1.382997,1.0,5.00,6.0,7.00,10.0
OverallCond,1460.0,5.575342,1.112799,1.0,5.00,5.0,6.00,9.0
YearBuilt,1460.0,1971.267808,30.202904,1872.0,1954.00,1973.0,2000.00,2010.0
YearRemodAdd,1460.0,1984.865753,20.645407,1950.0,1967.00,1994.0,2004.00,2010.0
MasVnrArea,1452.0,103.685262,181.066207,0.0,0.00,0.0,166.00,1600.0
BsmtFinSF1,1460.0,443.639726,456.098091,0.0,0.00,383.5,712.25,5644.0
BsmtFinSF2,1460.0,46.549315,161.319273,0.0,0.00,0.0,0.00,1474.0
BsmtUnfSF,1460.0,567.240411,441.866955,0.0,223.00,477.5,808.00,2336.0
TotalBsmtSF,1460.0,1057.429452,438.705324,0.0,795.75,991.5,1298.25,6110.0
1stFlrSF,1460.0,1162.626712,386.587738,334.0,882.00,1087.0,1391.25,4692.0
2ndFlrSF,1460.0,346.992466,436.528436,0.0,0.00,0.0,728.00,2065.0
LowQualFinSF,1460.0,5.844521,48.623081,0.0,0.00,0.0,0.00,572.0
GrLivArea,1460.0,1515.463699,525.480383,334.0,1129.50,1464.0,1776.75,5642.0
BsmtFullBath,1460.0,0.425342,0.518911,0.0,0.00,0.0,1.00,3.0
BsmtHalfBath,1460.0,0.057534,0.238753,0.0,0.00,0.0,0.00,2.0
FullBath,1460.0,1.565068,0.550916,0.0,1.00,2.0,2.00,3.0
HalfBath,1460.0,0.382877,0.502885,0.0,0.00,0.0,1.00,2.0
BedroomAbvGr,1460.0,2.866438,0.815778,0.0,2.00,3.0,3.00,8.0
KitchenAbvGr,1460.0,1.046575,0.220338,0.0,1.00,1.0,1.00,3.0
TotRmsAbvGrd,1460.0,6.517808,1.625393,2.0,5.00,6.0,7.00,14.0
Fireplaces,1460.0,0.613014,0.644666,0.0,0.00,1.0,1.00,3.0
GarageYrBlt,1379.0,1978.506164,24.689725,1900.0,1961.00,1980.0,2002.00,2010.0
GarageCars,1460.0,1.767123,0.747315,0.0,1.00,2.0,2.00,4.0
GarageArea,1460.0,472.980137,213.804841,0.0,334.50,480.0,576.00,1418.0
WoodDeckSF,1460.0,94.244521,125.338794,0.0,0.00,0.0,168.00,857.0
OpenPorchSF,1460.0,46.660274,66.256028,0.0,0.00,25.0,68.00,547.0
EnclosedPorch,1460.0,21.954110,61.119149,0.0,0.00,0.0,0.00,552.0
3SsnPorch,1460.0,3.409589,29.317331,0.0,0.00,0.0,0.00,508.0
ScreenPorch,1460.0,15.060959,55.757415,0.0,0.00,0.0,0.00,480.0
PoolArea,1460.0,2.758904,40.177307,0.0,0.00,0.0,0.00,738.0
MiscVal,1460.0,43.489041,496.123024,0.0,0.00,0.0,0.00,15500.0
MoSold,1460.0,6.321918,2.703626,1.0,5.00,6.0,8.00,12.0
YrSold,1460.0,2007.815753,1.328095,2006.0,2007.00,2008.0,2009.00,2010.0
SalePrice,1460.0,180921.195890,79442.502883,34900.0,129975.00,163000.0,214000.00,755000.0

In [ ]:
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()
        
        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
        #Return the dataframe with missing information
        return mis_val_table_ren_columns

In [ ]:
missing_values_table(train)

Your selected dataframe has 81 columns.
There are 19 columns that have missing values.

              Missing Values  % of Total Values
PoolQC                  1453               99.5
MiscFeature             1406               96.3
Alley                   1369               93.8
Fence                   1179               80.8
FireplaceQu              690               47.3
LotFrontage              259               17.7
GarageType                81                5.5
GarageYrBlt               81                5.5
GarageFinish              81                5.5
GarageQual                81                5.5
GarageCond                81                5.5
BsmtExposure              38                2.6
BsmtFinType2              38                2.6
BsmtFinType1              37                2.5
BsmtCond                  37                2.5
BsmtQual                  37                2.5
MasVnrArea                 8                0.5
MasVnrType                 8                0.5
Electrical                 1                0.1

In [ ]:
missing_values_table(test)

Your selected dataframe has 80 columns.
There are 33 columns that have missing values.

              Missing Values  % of Total Values
PoolQC                  1456               99.8
MiscFeature             1408               96.5
Alley                   1352               92.7
Fence                   1169               80.1
FireplaceQu              730               50.0
LotFrontage              227               15.6
GarageCond                78                5.3
GarageYrBlt               78                5.3
GarageQual                78                5.3
GarageFinish              78                5.3
GarageType                76                5.2
BsmtCond                  45                3.1
BsmtExposure              44                3.0
BsmtQual                  44                3.0
BsmtFinType1              42                2.9
BsmtFinType2              42                2.9
MasVnrType                16                1.1
MasVnrArea                15                1.0
MSZoning                   4                0.3
BsmtFullBath               2                0.1
BsmtHalfBath               2                0.1
Functional                 2                0.1
Utilities                  2                0.1
GarageCars                 1                0.1
GarageArea                 1                0.1
TotalBsmtSF                1                0.1
KitchenQual                1                0.1
BsmtUnfSF                  1                0.1
BsmtFinSF2                 1                0.1
BsmtFinSF1                 1                0.1
Exterior2nd                1                0.1
Exterior1st                1                0.1
SaleType                   1                0.1

In [ ]:
train1=train.copy()
test1=test.copy()

In [ ]:
train1.drop(['PoolQC','MiscFeature','Alley','Fence','FireplaceQu'],axis=1,inplace=True)
test1.drop(['PoolQC','MiscFeature','Alley','Fence','FireplaceQu'],axis=1,inplace=True)

In [ ]:
train1.shape,test1.shape

((1460, 76), (1459, 75))

In [ ]:
missing_values_table(train1)

Your selected dataframe has 76 columns.
There are 14 columns that have missing values.

              Missing Values  % of Total Values
LotFrontage              259               17.7
GarageType                81                5.5
GarageYrBlt               81                5.5
GarageFinish              81                5.5
GarageQual                81                5.5
GarageCond                81                5.5
BsmtExposure              38                2.6
BsmtFinType2              38                2.6
BsmtQual                  37                2.5
BsmtCond                  37                2.5
BsmtFinType1              37                2.5
MasVnrType                 8                0.5
MasVnrArea                 8                0.5
Electrical                 1                0.1

In [ ]:
train1.dropna(subset=['Electrical','MasVnrArea','MasVnrType'],inplace=True,how='any')

In [ ]:
missing_values_table(train1)

Your selected dataframe has 76 columns.
There are 11 columns that have missing values.

              Missing Values  % of Total Values
LotFrontage              257               17.7
GarageType                81                5.6
GarageYrBlt               81                5.6
GarageFinish              81                5.6
GarageQual                81                5.6
GarageCond                81                5.6
BsmtExposure              38                2.6
BsmtFinType2              38                2.6
BsmtQual                  37                2.5
BsmtCond                  37                2.5
BsmtFinType1              37                2.5

In [ ]:
from sklearn_pandas import CategoricalImputer
from sklearn.impute import SimpleImputer

In [ ]:
cat_imputer=CategoricalImputer()
mean_imputer=SimpleImputer(strategy='mean')

In [ ]:
num_cols=train1.select_dtypes(include=np.number).columns
cat_cols=train1.select_dtypes(include=object).columns
tnum_cols=test1.select_dtypes(include=np.number).columns
tcat_cols=test1.select_dtypes(include=object).columns

In [ ]:
num_cols,cat_cols

(Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
        'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
        'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
        'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
        'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
        'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
        'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
        'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
       dtype='object'),
 Index(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities',
        'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
        'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
        'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
        'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
        'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
        'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond',
        'PavedDrive', 'SaleType', 'SaleCondition'],
       dtype='object'))

In [ ]:
num_train=train1[num_cols]
cat_train=train1[cat_cols]
# num_test=test1[tnum_cols]
# cat_test=test1[tcat_cols]

In [ ]:
num_test=test1[tnum_cols]
cat_test=test1[tcat_cols]

In [ ]:
test1.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,12500,6,2010,WD,Normal

In [ ]:
mean_imputer.fit_transform(num_train)
mean_imputer.fit_transform(num_test)

array([[1.461e+03, 2.000e+01, 8.000e+01, ..., 0.000e+00, 6.000e+00,
        2.010e+03],
       [1.462e+03, 2.000e+01, 8.100e+01, ..., 1.250e+04, 6.000e+00,
        2.010e+03],
       [1.463e+03, 6.000e+01, 7.400e+01, ..., 0.000e+00, 3.000e+00,
        2.010e+03],
       ...,
       [2.917e+03, 2.000e+01, 1.600e+02, ..., 0.000e+00, 9.000e+00,
        2.006e+03],
       [2.918e+03, 8.500e+01, 6.200e+01, ..., 7.000e+02, 7.000e+00,
        2.006e+03],
       [2.919e+03, 6.000e+01, 7.400e+01, ..., 0.000e+00, 1.100e+01,
        2.006e+03]])

In [ ]:
test1['GarageType'] = cat_imputer.fit_transform(test1['GarageType'])
test1['GarageYrBlt'] = cat_imputer.fit_transform(test1['GarageYrBlt'])
test1['GarageFinish'] = cat_imputer.fit_transform(test1['GarageFinish'])

test1['GarageQual'] = cat_imputer.fit_transform(test1['GarageQual'])

test1['GarageCond'] = cat_imputer.fit_transform(test1['GarageCond'])

test1['BsmtCond'] = cat_imputer.fit_transform(test1['BsmtCond'])

test1['BsmtQual'] = cat_imputer.fit_transform(test1['BsmtQual'])

test1['BsmtExposure'] = cat_imputer.fit_transform(test1['BsmtExposure'])

test1['BsmtFinType1'] = cat_imputer.fit_transform(test1['BsmtFinType1'])

test1['BsmtFinType2'] = cat_imputer.fit_transform(test1['BsmtFinType2'])

test1['MasVnrType'] = cat_imputer.fit_transform(test1['MasVnrType'])

test1['MasVnrArea'] = cat_imputer.fit_transform(test1['MasVnrArea'])

test1['MSZoning'] = cat_imputer.fit_transform(test1['MSZoning'])

In [ ]:
test1['BsmtFullBath'] = cat_imputer.fit_transform(test1['BsmtFullBath'])
# From Faculty (Olympus) to Everyone 12:27 PM
train1['GarageType'] = cat_imputer.fit_transform(train1['GarageType'])
train1['GarageYrBlt'] = cat_imputer.fit_transform(train1['GarageYrBlt'])
train1['GarageFinish'] = cat_imputer.fit_transform(train1['GarageFinish'])

train1['GarageQual'] = cat_imputer.fit_transform(train1['GarageQual'])

train1['GarageCond'] = cat_imputer.fit_transform(train1['GarageCond'])

train1['BsmtCond'] = cat_imputer.fit_transform(train1['BsmtCond'])

train1['BsmtQual'] = cat_imputer.fit_transform(train1['BsmtQual'])

train1['BsmtExposure'] = cat_imputer.fit_transform(train1['BsmtExposure'])

train1['BsmtFinType1'] = cat_imputer.fit_transform(train1['BsmtFinType1'])

train1['BsmtFinType2'] = cat_imputer.fit_transform(train1['BsmtFinType2'])

In [ ]:
missing_values_table(test1)

Your selected dataframe has 75 columns.
There are 14 columns that have missing values.

              Missing Values  % of Total Values
LotFrontage              227               15.6
Utilities                  2                0.1
BsmtHalfBath               2                0.1
Functional                 2                0.1
Exterior1st                1                0.1
Exterior2nd                1                0.1
BsmtFinSF1                 1                0.1
BsmtFinSF2                 1                0.1
BsmtUnfSF                  1                0.1
TotalBsmtSF                1                0.1
KitchenQual                1                0.1
GarageCars                 1                0.1
GarageArea                 1                0.1
SaleType                   1                0.1

In [ ]:
missing_values_table(train1)

Your selected dataframe has 76 columns.
There are 0 columns that have missing values.

Empty DataFrame
Columns: [Missing Values, % of Total Values]
Index: []

In [ ]:
train1['LotFrontage']=mean_imputer.fit_transform(train1[['LotFrontage']])

In [ ]:
missing_values_table(test1)

Your selected dataframe has 75 columns.
There are 0 columns that have missing values.

Empty DataFrame
Columns: [Missing Values, % of Total Values]
Index: []

In [ ]:
test1['LotFrontage']=mean_imputer.fit_transform(test1[['LotFrontage']])

In [ ]:
test1['BsmtHalfBath']=mean_imputer.fit_transform(test1[['BsmtHalfBath']])

In [ ]:
test1['BsmtFinSF1']=mean_imputer.fit_transform(test1[['BsmtFinSF1']])

In [ ]:
test1['BsmtFinSF2']=mean_imputer.fit_transform(test1[['BsmtFinSF2']])

In [ ]:
test1['BsmtUnfSF']=mean_imputer.fit_transform(test1[['BsmtUnfSF']])

In [ ]:
test1['TotalBsmtSF']=mean_imputer.fit_transform(test1[['TotalBsmtSF']])

In [ ]:
test1['GarageCars']=mean_imputer.fit_transform(test1[['GarageCars']])

In [ ]:
test1['GarageArea']=mean_imputer.fit_transform(test1[['GarageArea']])

In [ ]:
test1['SaleType']=cat_imputer.fit_transform(test1['SaleType'])

In [ ]:
test1['KitchenQual']=cat_imputer.fit_transform(test1['KitchenQual'])

In [ ]:
test1['Utilities']=cat_imputer.fit_transform(test1['Utilities'])

In [ ]:
test1['Functional']=cat_imputer.fit_transform(test1['Functional'])

In [ ]:
test1['Exterior1st']=cat_imputer.fit_transform(test1['Exterior1st'])

In [ ]:
test1['Exterior2nd']=cat_imputer.fit_transform(test1['Exterior2nd'])

In [ ]:
train1.shape,test1.shape

((1451, 76), (1459, 75))

In [ ]:
combine=pd.concat([train1,test1],ignore_index=True)

In [ ]:
combine.shape

(2910, 76)

In [ ]:
dummydata=pd.get_dummies(combine,drop_first=True)

In [ ]:
dummydata.shape

(2910, 234)

In [ ]:
train_data=dummydata.iloc[:1451]
test_data=dummydata.iloc[1451:]

In [ ]:
test_data = test_data.drop(['SalePrice'], axis = 1)

In [ ]:
test_data.shape

(1459, 233)

In [ ]:
X_train = train_data.drop(['Id','SalePrice'], axis = 1)
y_train = train_data['SalePrice']

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 10)
principalcomp = pca.fit_transform(X_train)
principaltraindata = pd.DataFrame(data = principalcomp)

In [ ]:
principaltestcomp = pca.fit_transform(test_data)
principaltestdata = pd.DataFrame(data = principaltestcomp)

In [ ]:
from xgboost import XGBRegressor
model = XGBRegressor()

In [ ]:
model.fit(principaltraindata,y_train)

[08:24:03] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor()

In [ ]:
pred = model.predict(principaltestdata)

In [ ]:
test_pred = pd.DataFrame(pred)

In [ ]:
test_pred.columns = ['SalePrice']

In [ ]:
test_pred.head()

       SalePrice
0  116490.445312
1  434708.062500
2  256523.859375
3  214086.812500
4  181455.390625

In [ ]:
test_pred.index = test_data.index

In [ ]:
test_pred['Id'] = test_data['Id']

In [ ]:
test_pred.shape

(1459, 2)

In [ ]:
test_pred.head()

          SalePrice    Id
1451  116490.445312  1461
1452  434708.062500  1462
1453  256523.859375  1463
1454  214086.812500  1464
1455  181455.390625  1465

In [ ]:
test_pred.to_csv('submission.csv',index=False)